-- Don Bosco - Perfectionnement V79 — Notifications Push
-- À exécuter dans Supabase SQL Editor avant le déploiement des fonctions.

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  user_agent text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_used_at timestamptz,
  unique(profile_id, endpoint)
);

create index if not exists push_subscriptions_profile_idx on public.push_subscriptions(profile_id);
create index if not exists push_subscriptions_active_idx on public.push_subscriptions(active);

create table if not exists public.push_notification_log (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  notification_type text not null,
  event_key text not null,
  title text not null,
  body text not null,
  created_at timestamptz not null default now(),
  unique(profile_id, notification_type, event_key)
);

create index if not exists push_notification_log_profile_idx on public.push_notification_log(profile_id);
create index if not exists push_notification_log_created_idx on public.push_notification_log(created_at desc);

alter table public.push_subscriptions enable row level security;
alter table public.push_notification_log enable row level security;

-- Un utilisateur ne voit/modifie que ses propres abonnements.
drop policy if exists push_subscriptions_select_own on public.push_subscriptions;
create policy push_subscriptions_select_own
on public.push_subscriptions for select to authenticated
using (profile_id = auth.uid());

drop policy if exists push_subscriptions_insert_own on public.push_subscriptions;
create policy push_subscriptions_insert_own
on public.push_subscriptions for insert to authenticated
with check (profile_id = auth.uid());

drop policy if exists push_subscriptions_update_own on public.push_subscriptions;
create policy push_subscriptions_update_own
on public.push_subscriptions for update to authenticated
using (profile_id = auth.uid())
with check (profile_id = auth.uid());

drop policy if exists push_subscriptions_delete_own on public.push_subscriptions;
create policy push_subscriptions_delete_own
on public.push_subscriptions for delete to authenticated
using (profile_id = auth.uid());

-- Le journal est écrit uniquement par la fonction serveur avec la service role key.
-- Aucun accès client n'est accordé.
revoke all on public.push_notification_log from anon, authenticated;
revoke all on public.push_subscriptions from anon;
grant select, insert, update, delete on public.push_subscriptions to authenticated;

drop trigger if exists set_push_subscriptions_updated_at on public.push_subscriptions;
create trigger set_push_subscriptions_updated_at
before update on public.push_subscriptions
for each row execute function public.set_updated_at();

-- Extensions utilisées par le planificateur Supabase.
create extension if not exists pg_cron with schema extensions;
create extension if not exists pg_net with schema extensions;

-- IMPORTANT : avant d'activer le job, renseigner dans Vault :
--   project_url       = https://zshvrarmooukeosyxbgx.supabase.co
--   push_cron_secret  = la valeur PUSH_CRON_SECRET fournie dans le guide V79
-- Puis créer le job avec le SQL suivant :
--
-- select cron.schedule(
--   'don-bosco-push-dispatch',
--   '*/5 * * * *',
--   $$
--   select net.http_post(
--     url := (select decrypted_secret from vault.decrypted_secrets where name = 'project_url') || '/functions/v1/push-notifications',
--     headers := jsonb_build_object(
--       'Content-Type','application/json',
--       'x-cron-secret',(select decrypted_secret from vault.decrypted_secrets where name = 'push_cron_secret')
--     ),
--     body := '{"action":"dispatch"}'::jsonb
--   );
--   $$
-- );
